name: Build / Deploy Site

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: npm run build
      - name: Deploy to https://rawprotorust.surge.sh
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: 'rawprotorust.surge.sh'
          project: 'pkg'
          login: ${{ secrets.SURGE_LOGIN }}
          token: ${{ secrets.SURGE_TOKEN }}