name: Build / Deploy Site

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Build wasm
        run: npm run build
      - name: Deploy demo-site to https://rawprotorust.surge.sh
        run: npm run deploy
